apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-authen-proxy
  labels:
    name: payment-authen-proxy
    module: trm-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: payment-authen-proxy
      module: trm-app
      environment: development
  template:
    metadata:
      labels:
        name: payment-authen-proxy
        module: trm-app
        environment: development
      annotations:
        prometheus.io/scrape: 'false'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: payment-authen-proxy
          image: reghbpr01.dc1.true.th/bss-payments/payment-authen-proxy:1.0
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: FASTIFY_PORT
              value: '3000'
            - name: FASTIFY_PRETTY_LOGS
              value: 'false'
            - name: DB_HOST
              value: '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= 172.19.191.204)(PORT=1540)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=TRMPRD)))'
            - name: DB_USER
              value: 'trmapp'
            - name: DB_PASS
              value: 'appimrt'
          resources:
            requests:
              memory: '512Mi'
              cpu: '50m'
            limits:
              memory: '1Gi'
              cpu: '800m'
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: payment-authen-proxy
  labels:
    name: payment-authen-proxy
    module: trm-app
    environment: development
spec:
  selector:
    name: payment-authen-proxy
    module: trm-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
