apiVersion: v1
kind: Pod
metadata:
  name: pas-reconnect-batch
  namespace: payment
spec:
  containers:
    - name: pas-reconnect-batch
      image: pawatiamsupa/pas-reconnect-batch:latest
      # command: ["node app.js"]
      # args: ["--system=DCPAL0050P04", "--actionType=RERUN"]
      # args:
      # - sleep
      # - "1000000"
      resources:
        requests:
          memory: "256Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      imagePullPolicy: Always
      env:
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: http_proxy
          value: ""
        - name: https_proxy
          value: ""
        - name: TZ
          value: "Asia/Bangkok"
        
  restartPolicy: OnFailure
  #imagePullSecrets:
  #  - name: regcred
