apiVersion: v1
kind: Service
metadata:
  name: payment-tiller
  labels:
    app: helm
    name: tiller
spec:
  selector:
    app: helm
    name: tiller
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - port: 44134
      name: http
      targetPort: 44134
      protocol: TCP
