server:
  port: 8080
app:
  GlobalConfig:
    decodeThaiName: true
    header:
      mockHeader: false
  endpoint:
    service-host: http://tsm-paymentreport-service
    serviceCashPaymentHost: http://cash-management-service
  configNotUseReport:
      startTime: '10:00:00'
      endTime: '21:00:00'
      isBlockTime: 'N'