apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartconnect-service
  labels:
    name: smartconnect-service
    module: trm-app
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      name: smartconnect-service
      module: trm-app
      environment: production
  template:
    metadata:
      labels:
        name: smartconnect-service
        module: trm-app
        environment: production
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: smartconnect-service
          image: reghbpr01.dc1.true.th/bss-payments/smartconnect-service:latest
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              cpu: '500m'
              memory: '512Mi'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: app-port
          #   initialDelaySeconds: 150
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 5
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: app-port
          #   initialDelaySeconds: 150
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 5
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: smartconnect-service
  labels:
    name: smartconnect-service
    module: trm-app
    environment: production
spec:
  selector:
    name: smartconnect-service
    module: trm-app
    environment: production
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
