apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-report-service
  labels:
    name: cash-report-service
    module: tsm-app
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cash-report-service
      module: tsm-app
      environment: production
  template:
    metadata:
      labels:
        name: cash-report-service
        module: tsm-app
        environment: production
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: cash-report-service
          image: reghbpr01.dc1.true.th/bss-payments/cash-report-service:latest
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
          resources:
            requests:
              memory: '512Mi'
              cpu: '50m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: cash-report-service
  labels:
    name: cash-report-service
    module: tsm-app
    environment: production
spec:
  selector:
    name: cash-report-service
    module: tsm-app
    environment: production
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
