server:
  port: 8080
app:
  GlobalConfig:
    header:
      mockHeader: false
  endpoint:
    serviceHost: http://trm-report-service
    cashManagementHost: http://cash-management-service
    pssTrmHost: http://172.19.192.116:8980
zuul:
  routes:
    pss-trm-web:
      path: /pss-trm-web2/**
      url: http://172.19.192.116:8980/pss-trm-web
    pss-smartui-web:
      path: /pss-smartui-web/**
      url: http://172.19.192.116:8980/pss-smartui-web
    trm-cashmanagement-api-service:
      path: /trm-cashmanagement-api-service/**
      url: http://trm-cashmanagement-api-service
    common:
      path: /common/**
      url: http://trm-common-service/common
