server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:oracle:thin:@172.19.191.204:1540:TRMPRD
    username: trmappall
    password: appimrt
    driver-class-name: oracle.jdbc.driver.OracleDriver
app:
  endpoint:
    reportExportHost: http://trm-direct-reportexport-service
