apiVersion: apps/v1
kind: Deployment
metadata:
  name: trm-common-service
  labels:
    name: trm-common-service
    module: trm-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: trm-common-service
      module: trm
      environment: development
  template:
    metadata:
      labels:
        name: trm-common-service
        module: trm
        environment: development
      annotations:
        prometheus.io/scrape: 'false'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: trm-common-service
          image: reghbpr01.dc1.true.th/bss-payments/trm-common-service:1.0
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: NODE_CONNECT_STRING
              value: '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.19.191.204)(PORT=1540)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=TRMPRD)))'
            - name: NODE_USER
              value: 'trmapp'
            - name: NODE_PASSWORD
              value: 'appimrt'
          resources:
            requests:
              memory: '512Mi'
              cpu: '50m'
            limits:
              memory: '1Gi'
              cpu: '800m'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: trm-common-service
  labels:
    name: trm-common-service
    module: trm
    environment: development
spec:
  selector:
    name: trm-common-service
    module: trm
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
