apiVersion: apps/v1
kind: Deployment
metadata:
  name: trm-direct-reportexport-service
  labels:
    name: trm-direct-reportexport-service
    module: trm-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: trm-direct-reportexport-service
      module: trm-app
      environment: development
  template:
    metadata:
      labels:
        name: trm-direct-reportexport-service
        module: trm-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: trm-direct-reportexport-service
          image: reghbpr01.dc1.true.th/bss-payments/trm-direct-reportexport-service:latest
          volumeMounts:
            - mountPath: /report
              name: report-data
              subPath: trm-direct-report-data
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
          resources:
            requests:
              memory: '256Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
              cpu: '800m'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 180
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
      volumes:
        - name: report-data
          persistentVolumeClaim:
            claimName: payment-nfs
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: trm-direct-reportexport-service
  labels:
    name: trm-direct-reportexport-service
    module: trm-app
    environment: development
spec:
  selector:
    name: trm-direct-reportexport-service
    module: trm-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
