server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@172.19.192.114:1553:TRMUAT
    username: trmapp
    password: freewill
    driver-class-name: oracle.jdbc.driver.OracleDriver
app:
  endpoint:
    reportExportHost: http://trm-reportexport-service
