apiVersion: apps/v1
kind: Deployment
metadata:
  name: trm-direct-report-web2
  labels:
    name: trm-direct-report-web2
    module: trm-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trm-direct-report-web2
      module: trm-app
      environment: development
  template:
    metadata:
      labels:
        name: trm-direct-report-web2
        module: trm-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: trm-direct-report-web2
          image: reghbpr01.dc1.true.th/bss-payments/trm-direct-report-web2:latest
          volumeMounts:
            - mountPath: /report
              name: report-data
              subPath: trm-direct-report-data
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
          resources:
            requests:
              memory: '256Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      volumes:
        - name: report-data
          persistentVolumeClaim:
            claimName: payment-nfs
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: trm-direct-report-web2
  labels:
    name: trm-direct-report-web2
    module: trm-app
    environment: development
spec:
  selector:
    name: trm-direct-report-web2
    module: trm-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
