server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  datasource:
    tomcat:
      max-active: 5
    url: jdbc:oracle:thin:@172.19.192.114:1553:TRMUAT
    username: trmapp
    password: freewill
    driver-class-name: oracle.jdbc.driver.OracleDriver
app:
  endpoint:
    reportExportHost: http://trm-direct-reportexport-service
