apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-cdn
  labels:
    name: payment-cdn
    module: trm-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: payment-cdn
      module: trm-app
      environment: development
  template:
    metadata:
      labels:
        name: payment-cdn
        module: trm-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: payment-cdn
          image: reghbpr01.dc1.true.th/bss-payments/payment-cdn:1.3.6-dealer
          #image: reghbpr01.dc1.true.th/bss-payments/payment-cdn:1.3.3 shop 
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '400m'
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: payment-cdn
  labels:
    name: payment-cdn
    module: trm-app
    environment: development
spec:
  selector:
    name: payment-cdn
    module: trm-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
