apiVersion: apps/v1
kind: Deployment
metadata:
  name: pas-backout-service
  labels:
    name: pas-backout-service
    module: noncounter-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pas-backout-service
      module: noncounter-app
      environment: development
  template:
    metadata:
      labels:
        name: pas-backout-service
        module: noncounter-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: pas-backout-service
          image: reghbpr01.dc1.true.th/bss-payments/pas-backout-service:latest
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
            - name: EXPRESS_PORT
              value: '8080'
            - name: DEBUG
              value: debug
            - name: Q_NAME
              value: 'CCBS_BACKOUT'
            - name: Q_HOST
              value: '172.19.217.40'
            - name: Q_PORT
              value: '5672'
            - name: Q_LOGIN
              value: appadm
            - name: Q_PASSWORD
              value: 'P@ssword123'
            - name: Q_TTL
              value: '15'
            - name: Q_CONNECTION_TIMEOUT
              value: '10000'
          resources:
            requests:
              memory: '256Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pas-backout-service
  labels:
    name: pas-backout-service
    module: noncounter-app
    environment: development
spec:
  selector:
    name: pas-backout-service
    module: noncounter-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
