apiVersion: v1
kind: Pod
metadata:
  name: busybox-loadfile
  namespace: payment
spec:
  containers:
  - name: payment-happyhome-batch
    image: busybox
    #command: ["bash"]
    #args: ["/opt/app-root/src/export/data/datawarehouse"]
    args:
    - sleep
    - "1000000"
    resources:
      requests:
        memory: '256Mi'
        cpu: '50m'
      limits:
        memory: '256Mi'
        cpu: '800m'
    volumeMounts:
      - mountPath: /opt/app-root/src/export/data/datawarehouse
        name: happyhome-data
        subPath: happy-home-data

      - mountPath: /opt/app-root/src/export/data/commission
        name: happyhome-data
        subPath: happy-home-data-cms

      - mountPath: /opt/app-root/src/certs
        name: happyhome-config

      - mountPath: /opt/app-root/src/source
        name: happyhome-data
        subPath: happyhome-source-file
      
      - mountPath: /opt/app-root/src/target
        name: happyhome-data
        subPath: happyhome-target-file
  restartPolicy: OnFailure
  volumes:
    - name: happyhome-data
      persistentVolumeClaim:
        claimName: payment-nfs
    - name: happyhome-config
      configMap:
        name: happyhome-config
  imagePullSecrets:
    - name: regcred