apiVersion: v1
kind: ConfigMap
metadata:
  name: happyhome-config
  namespace: payment
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDATCCAemgAwIBAgIJAJ+PpT9E+5r3MA0GCSqGSIb3DQEBCwUAMCsxEjAQBgNV
    BAoMCUNvY2tyb2FjaDEVMBMGA1UEAwwMQ29ja3JvYWNoIENBMCAXDTE5MTAyNDE3
    MTQ1NFoYDzIxMTkwOTMwMTcxNDU0WjArMRIwEAYDVQQKDAlDb2Nrcm9hY2gxFTAT
    BgNVBAMMDENvY2tyb2FjaCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBALsCUTNpAs5g9CqUqbGugBiK+GNwXQCy3XS8FitbtuqhT2EI48BiSv1NVNmq
    qoy8vveQisTpTeglM6T5JESR2Xxaw7vi6a5PbD4c2xJ2ohEbjNg/c15Wn0jo5+K7
    qYl+T1YI5FrY+IZb/A3Pgl4rH0IPzm5zEtFbYDf+Hj8kD50Ek0tD5mQsMtc7ut0r
    y+CfuOILERSRb9Ah9+pYPNU/ykpTJZArjh4wtwiXIXn3uTVShoih6yUMFgdcy8lF
    vB3IoupWLKSjVd1GHBp0l7ZXUB26U29pZCGyHzWc6L5GxgB80kvc6IA1Q4pEzu/Q
    2+3maLqQRPn17b5dBnYL9bqycdcCAwEAAaMmMCQwDgYDVR0PAQH/BAQDAgLkMBIG
    A1UdEwEB/wQIMAYBAf8CAQEwDQYJKoZIhvcNAQELBQADggEBAKL6E3MmJfbwPEDJ
    6bGQ66iD+RwTxjzsOJcuAjVEq34lwtlPI7kc97pY3xoOfyJlbUyE79aIxoxCPo/8
    6Gjd9YJp0v1A4EuAvRsLeDwVxMNzDXEkDzqnUV3++KZiu96KoqImiZ7pnrQdKbfM
    I7O6sm6WnaAYiQN485h6WX3NYJ5zcZ58V+mXfcHZCM1RwgeAm4BMfRtW1zpXOLLe
    VdX/A1n9m1RV7DphJ80to4xsb9byBav/MCbpnOYmEGHxK1aOccU5XJE7c8O7ur9+
    84SEIuE9M5jSh8GhWL61rpYBUGnXrn8lxbT54H9tpnu4Z1ABkI2u+4taXHJksY5X
    4j2VAYQ=
    -----END CERTIFICATE-----
  client.payment-appc.crt: |
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 13 (0xd)
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: O=Cockroach, CN=Cockroach CA
            Validity
                Not Before: Dec 17 11:04:10 2019 GMT
                Not After : Nov 23 11:04:10 2119 GMT
            Subject: O=Cockroach, CN=payment-appc
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        00:c4:79:47:38:50:75:06:87:21:14:ea:94:f2:70:
                        91:52:bd:e4:a0:4c:f8:09:e5:f9:df:a9:1b:89:23:
                        14:ee:1b:be:4e:72:b2:94:b5:65:ea:35:79:cb:32:
                        cb:09:b6:f0:4c:9e:d9:5b:c0:e9:f0:e3:66:a3:69:
                        ce:68:60:77:3d:ff:da:19:f9:01:fe:3d:90:ab:c9:
                        23:d9:6c:a1:12:70:fe:96:bb:16:bf:fe:31:b9:1d:
                        49:34:b3:ef:a6:3d:1c:85:b7:1a:12:3b:0f:8e:85:
                        1d:38:12:fc:02:97:2c:82:38:e9:c3:c0:c7:f4:e2:
                        8b:ec:48:a9:38:e7:9d:d8:d0:05:ab:95:10:b1:e9:
                        3a:f9:98:49:9c:a2:59:70:46:07:df:19:d7:e9:f7:
                        f5:52:fc:76:b6:0a:df:ec:5c:4e:36:ee:93:29:6a:
                        24:f3:cf:ed:d0:ab:c7:01:ab:98:fc:fd:24:df:e4:
                        2a:1e:35:58:1c:6d:b6:35:45:36:90:6e:82:3a:35:
                        39:85:5b:ad:fc:cb:98:ca:05:1b:e5:50:54:75:d4:
                        c8:fd:ef:32:ad:8b:3f:bc:7a:08:c8:ff:15:d4:d2:
                        d9:9e:60:7f:f5:9d:fe:97:3d:34:78:01:e0:57:51:
                        19:50:cc:24:d3:59:46:4e:61:74:9b:f6:71:4f:36:
                        69:af
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Key Usage: critical
                    Digital Signature, Key Encipherment
                X509v3 Extended Key Usage: 
                    TLS Web Client Authentication
        Signature Algorithm: sha256WithRSAEncryption
            9e:c2:4d:02:bf:27:cf:ab:f2:4c:cb:64:ea:4d:64:d1:f4:5e:
            9f:e6:7e:c8:41:e7:70:87:e7:3f:69:48:5a:ff:c9:22:b0:5a:
            c7:30:4e:95:12:e4:29:28:70:87:49:c2:74:97:ad:ec:b0:37:
            a9:47:5f:02:f1:b7:e6:3c:d3:f9:e6:ce:b6:f1:56:6a:c8:6e:
            80:ee:b8:ac:63:9b:51:4c:8f:b0:6e:cd:2f:30:1c:4b:a1:09:
            1a:6c:6b:f9:ba:32:aa:7e:3b:62:ce:3e:bf:ce:52:43:14:4e:
            3b:cd:08:10:4e:72:02:d8:11:22:cc:72:3c:a4:d7:82:77:65:
            91:23:c7:2d:af:e3:8b:56:c9:14:a3:9d:d6:ff:f6:c3:6d:24:
            04:48:84:2f:cb:3e:f3:12:1b:d8:c5:69:1d:5b:9e:72:e6:27:
            ad:3a:df:da:1b:d0:2f:05:e8:c8:57:2f:f4:11:06:d6:cb:4d:
            4e:b0:f7:78:f5:0d:69:4e:93:35:af:4b:a7:87:19:61:45:ab:
            3f:88:93:78:8b:de:70:34:cd:29:11:9e:09:c3:ef:7a:15:c1:
            cb:e8:13:31:8f:a0:de:8c:7e:93:e6:1d:49:19:af:4e:0d:69:
            48:8d:84:85:12:b9:b4:96:4e:b1:42:ad:7f:1e:df:60:1d:1a:
            b1:57:fc:88
    -----BEGIN CERTIFICATE-----
    MIIC+jCCAeKgAwIBAgIBDTANBgkqhkiG9w0BAQsFADArMRIwEAYDVQQKDAlDb2Nr
    cm9hY2gxFTATBgNVBAMMDENvY2tyb2FjaCBDQTAgFw0xOTEyMTcxMTA0MTBaGA8y
    MTE5MTEyMzExMDQxMFowKzESMBAGA1UECgwJQ29ja3JvYWNoMRUwEwYDVQQDDAxw
    YXltZW50LWFwcGMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEeUc4
    UHUGhyEU6pTycJFSveSgTPgJ5fnfqRuJIxTuG75OcrKUtWXqNXnLMssJtvBMntlb
    wOnw42ajac5oYHc9/9oZ+QH+PZCrySPZbKEScP6Wuxa//jG5HUk0s++mPRyFtxoS
    Ow+OhR04EvwClyyCOOnDwMf04ovsSKk4553Y0AWrlRCx6Tr5mEmcollwRgffGdfp
    9/VS/Ha2Ct/sXE427pMpaiTzz+3Qq8cBq5j8/STf5CoeNVgcbbY1RTaQboI6NTmF
    W638y5jKBRvlUFR11Mj97zKtiz+8egjI/xXU0tmeYH/1nf6XPTR4AeBXURlQzCTT
    WUZOYXSb9nFPNmmvAgMBAAGjJzAlMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
    BggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAnsJNAr8nz6vyTMtk6k1k0fRe
    n+Z+yEHncIfnP2lIWv/JIrBaxzBOlRLkKShwh0nCdJet7LA3qUdfAvG35jzT+ebO
    tvFWashugO64rGObUUyPsG7NLzAcS6EJGmxr+boyqn47Ys4+v85SQxROO80IEE5y
    AtgRIsxyPKTXgndlkSPHLa/ji1bJFKOd1v/2w20kBEiEL8s+8xIb2MVpHVuecuYn
    rTrf2hvQLwXoyFcv9BEG1stNTrD3ePUNaU6TNa9Lp4cZYUWrP4iTeIvecDTNKRGe
    CcPvehXBy+gTMY+g3ox+k+YdSRmvTg1pSI2EhRK5tJZOsUKtfx7fYB0asVf8iA==
    -----END CERTIFICATE-----
  client.payment-appc.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAxHlHOFB1BochFOqU8nCRUr3koEz4CeX536kbiSMU7hu+TnKy
    lLVl6jV5yzLLCbbwTJ7ZW8Dp8ONmo2nOaGB3Pf/aGfkB/j2Qq8kj2WyhEnD+lrsW
    v/4xuR1JNLPvpj0chbcaEjsPjoUdOBL8Apcsgjjpw8DH9OKL7EipOOed2NAFq5UQ
    sek6+ZhJnKJZcEYH3xnX6ff1Uvx2tgrf7FxONu6TKWok88/t0KvHAauY/P0k3+Qq
    HjVYHG22NUU2kG6COjU5hVut/MuYygUb5VBUddTI/e8yrYs/vHoIyP8V1NLZnmB/
    9Z3+lz00eAHgV1EZUMwk01lGTmF0m/ZxTzZprwIDAQABAoIBAQCskkn4MNNZdH+e
    O52whSdgIeMa2gBT0Wh1B7hj8CiGLGAvz5cD/4ERAv+Dd43XbpQK+Mu6R+wz5clV
    Z64hB/o0vvH3NjyF79WOzhFq/HtOE2nLQ3FsGf3attqCLDonLi5LVNTVhoLXkBxm
    EGbCb75sc0kA4+e+NO7qD7hzfx2qPSFUGqbuT9ifvs5xFk7vcSkhSX3hQ72HAnLs
    D5h91SXCgvq+Ya2Bczgi4vTZYW6kKy/9PrKqj8ASab8v6Lhk9MhyEczGIsxWFyGg
    aj5Hy49ulGkdpUfHaHC+orTHHOke0+W1QCNd0AZRYGv6hIyME1ypXEY37/B8oDFR
    yxEgQN0hAoGBAPkpLg8hyHvTFmJA2k+iDsanruud0DGMxdfkPYJ5E17EQO3wmyEk
    uhwweV4ECuv5ylShs6tleENRY9jzTgjSYnBzseLndHBrcnzLHvtbmLP2DCrJNQxq
    nawj1NKLLljopSC5FOuI4AU12wk0EjylpbXxo6tJ0kINuv6caN0zDCCNAoGBAMnd
    33oPiZTVG6S4x0X1tO5GFPP4U6xQ94O70lx7vsDFe3miEEz182Ppi2i9fQ/3CmDr
    CD03okL7M+j9sTIg90koSeKmun2M68eyNipG9xVYSwMPUwDLgpx6Hz8OgdfbKvr5
    8J9Wpqb+aWKhDwFiptAqVrXAbqBLUg/PXHfdQTorAoGBAJcpNJhZlpgI6HuTfN7z
    IqPC94xaogRts1nXTrnpWqcTyZCReIwTDBYuEnPHYBjp4qaVs7s4RE4TAtCMS7tu
    Z+pxRmqyoSHTDhJH6PP2Dh6gF6GdkGGIDUByPJu/dM7b1dKUduyujbqbgdeDj8zb
    cj1/7BvvHXCVg+0UV0pbve/BAoGAW3He4nRXZsyDEUODQfXkWGv24e4EOXMULODQ
    koScDMdo/9iiebqQ3xnUxUXReYH3eZ/+w3yITL9u7IS/2G2Gl+VgUwQkRuung3b/
    gndTRqAQmvo+J4YJTMkljnML7rSh6799eTDPnaZyJvO+0GnYF0SWsw7RDlwQeIj+
    4m2gNrECgYEAr6fJqCGECmgWddbSukWXigEZMTRk+Y0lOWOib/vQMLnFifRJ9gsc
    H8yH5LKR4UOperM0oZTG6E3APzFEp5ZCgeIsHKrbWVfNx3re14iiTroRJ2v8HE6h
    qPDBSfEUAguCWnfoPl+d/RogVXRbl6V6TI4+5da5p7qf+JUPyxeMWkU=
    -----END RSA PRIVATE KEY-----
