apiVersion: apps/v1
kind: Deployment
metadata:
  name: trm-afterpayment-web2
  labels:
    name: trm-afterpayment-web2
    module: trm-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trm-afterpayment-web2
      module: trm-app
      environment: development
  template:
    metadata:
      labels:
        name: trm-afterpayment-web2
        module: trm-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: trm-afterpayment-web2
          image: reghbpr01.dc1.true.th/bss-payments/trm-afterpayment-web:latest
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
            - name: SPRING_PROFILES_ACTIVE
              value: 'uatkube'
            - name: ROUTER_DEFAULT_CONNECT_TIMEOUT
              value: '30m'
            - name: ROUTER_DEFAULT_CLIENT_TIMEOUT
              value: '30m'
            - name: ROUTER_DEFAULT_SERVER_TIMEOUT
              value: '30m'
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: trm-afterpayment-web2
  labels:
    name: trm-afterpayment-web2
    module: trm-app
    environment: development
spec:
  selector:
    name: trm-afterpayment-web2
    module: trm-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
