apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivr-payment-service
  labels:
    name: ivr-payment-service
    module: noncounter-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ivr-payment-service
      module: noncounter-app
      environment: development
  template:
    metadata:
      labels:
        name: ivr-payment-service
        module: noncounter-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: ivr-payment-service
          image: reghbpr01.dc1.true.th/bss-payments/ivr-payment-service:latest
          env:
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: TZ
              value: 'Asia/Bangkok'
            - name: EXPRESS_PORT
              value: '8080'
            - name: DB_CONNECTTION_STRING
              value: '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.19.193.48)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=pasdb)))'
            - name: DB_USER
              value: 'pmclto'
            - name: DB_PASSWORD
              value: 'pmclto'
            - name: MCP_URL_PROXY
              value: 'http://mcp-proxy-payment-uat.apps.true.th/api/v1/mcpProxy/callMCP'
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ivr-payment-service
  labels:
    name: ivr-payment-service
    module: noncounter-app
    environment: development
spec:
  selector:
    name: ivr-payment-service
    module: noncounter-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
