apiVersion: apps/v1
kind: Deployment
metadata:
  name: pas-report-service
  labels:
    name: pas-report-service
    module: pas-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pas-report-service
      module: pas-app
      environment: development
  template:
    metadata:
      labels:
        name: pas-report-service
        module: pas-app
        environment: development
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: pas-report-service
          image: reghbpr01.dc1.true.th/bss-payments/pas-report-service:1.0
          env:
            - name: TZ
              value: 'Asia/Bangkok'
            - name: http_proxy
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: https_proxy
              value: ''
            - name: HTTPS_PROXY
              value: ''
            - name: FASTIFY_PORT
              value: '8080'
            - name: FASTIFY_PRETTY_LOGS
              value: 'false'
            - name: DB_HOST
              value: '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.1.200)(PORT=1542))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PCSPRD)))'
            - name: DB_USER
              value: 'pas'
            - name: DB_PASS
              value: 'allocateall'
            - name: MCP_URL_PROXY
              value: 'http://mcp-proxy/api/v1/mcpProxy/callMCP'
            - name: MCP_UESR_ID
              value: 'CSOL'
            - name: MCP_PASSWORD
              value: 'CSOL@dI8qisZqMKk='
            - name: MCP_OPERATOR_ID
              value: 'PAS System'
            - name: MCP_TIMEOUT
              value: '10'
            - name: JAR_TIMEOUT_MILLISEC
              value: '20000'
          resources:
            requests:
              memory: '512Mi'
              cpu: '50m'
            limits:
              memory: '1Gi'
              cpu: '800m'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pas-report-service
  labels:
    name: pas-report-service
    module: pas-app
    environment: development
spec:
  selector:
    name: pas-report-service
    module: pas-app
    environment: development
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
